#MainWindow.py
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mlprep_landslide_detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 765)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Widget_Map_Area = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Widget_Map_Area.sizePolicy().hasHeightForWidth())
        self.Widget_Map_Area.setSizePolicy(sizePolicy)
        self.Widget_Map_Area.setMinimumSize(QtCore.QSize(0, 0))
        self.Widget_Map_Area.setStyleSheet("QWidget {\n"
"    background-color:#ffffff;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font: 600 12px \"Arial\";\n"
"    color: #E0E0E0;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    margin-top: 16px;\n"
"    background-color: transparent;\n"
"    padding: 12px;\n"
"    font-weight: 10;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 8px;\n"
"    background-color: #ffffff;    /* same as box background */\n"
"    color: black;\n"
"\n"
"    position:absolute;\n"
"    margin-top:10px\n"
"}")
        self.Widget_Map_Area.setObjectName("Widget_Map_Area")
        self.gridLayout = QtWidgets.QGridLayout(self.Widget_Map_Area)
        self.gridLayout.setObjectName("gridLayout")
        self.GroupBox_Pre_Event = QtWidgets.QGroupBox(self.Widget_Map_Area)
        self.GroupBox_Pre_Event.setObjectName("GroupBox_Pre_Event")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GroupBox_Pre_Event)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GraphicsView_Pre_Event = QtWidgets.QGraphicsView(self.GroupBox_Pre_Event)
        self.GraphicsView_Pre_Event.setObjectName("GraphicsView_Pre_Event")
        self.horizontalLayout_2.addWidget(self.GraphicsView_Pre_Event)
        self.gridLayout.addWidget(self.GroupBox_Pre_Event, 0, 0, 1, 1)
        self.GroupBox_Post_Event = QtWidgets.QGroupBox(self.Widget_Map_Area)
        self.GroupBox_Post_Event.setObjectName("GroupBox_Post_Event")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.GroupBox_Post_Event)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.GraphicsView_Post_Event = QtWidgets.QGraphicsView(self.GroupBox_Post_Event)
        self.GraphicsView_Post_Event.setObjectName("GraphicsView_Post_Event")
        self.horizontalLayout_11.addWidget(self.GraphicsView_Post_Event)
        self.gridLayout.addWidget(self.GroupBox_Post_Event, 0, 1, 1, 1)
        self.GroupBox_NDVI = QtWidgets.QGroupBox(self.Widget_Map_Area)
        self.GroupBox_NDVI.setObjectName("GroupBox_NDVI")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.GroupBox_NDVI)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.GraphicsView_NDVI = QtWidgets.QGraphicsView(self.GroupBox_NDVI)
        self.GraphicsView_NDVI.setObjectName("GraphicsView_NDVI")
        self.horizontalLayout_12.addWidget(self.GraphicsView_NDVI)
        self.gridLayout.addWidget(self.GroupBox_NDVI, 1, 0, 1, 1)
        self.GroupBox_Result = QtWidgets.QGroupBox(self.Widget_Map_Area)
        self.GroupBox_Result.setObjectName("GroupBox_Result")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.GroupBox_Result)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.GraphicsView_Result = QtWidgets.QGraphicsView(self.GroupBox_Result)
        self.GraphicsView_Result.setObjectName("GraphicsView_Result")
        self.horizontalLayout_13.addWidget(self.GraphicsView_Result)
        self.gridLayout.addWidget(self.GroupBox_Result, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.Widget_Map_Area)
        self.GridLayout_Inputs_Area = QtWidgets.QGridLayout()
        self.GridLayout_Inputs_Area.setObjectName("GridLayout_Inputs_Area")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background-color:#D7D5D2;")
        
        # --- FIXED LINE BELOW (Removed C++ syntax) ---
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 511, 701))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Widget_Inputs = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.Widget_Inputs.setStyleSheet("QGroupBox {\n"
"    font: 600 12px \"Arial\";\n"
"    color: #E0E0E0;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    margin-top: 16px;\n"
"    background-color: transparent;\n"
"    padding: 12px;\n"
"    font-weight: 10;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 8px;\n"
"    background-color: #D7D5D2;    /* same as box background */\n"
"    color: black;\n"
"\n"
"    position:absolute;\n"
"    margin-top:10px\n"
"}\n"
"\n"
"QLabel {\n"
"    color: black;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    border: 1px solid #555;\n"
"    border-radius: 6px;\n"
"    background-color: #ffffff;\n"
"    color:black;\n"
"    height:25;\n"
"}")
        self.Widget_Inputs.setObjectName("Widget_Inputs")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Widget_Inputs)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Lable_Landslide = QtWidgets.QLabel(self.Widget_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lable_Landslide.sizePolicy().hasHeightForWidth())
        self.Lable_Landslide.setSizePolicy(sizePolicy)
        self.Lable_Landslide.setMinimumSize(QtCore.QSize(250, 35))
        self.Lable_Landslide.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Lable_Landslide.setStyleSheet("QLabel {\n"
"    color: black;\n"
"    font: 700 16pt \"Arial\";\n"
"}")
        self.Lable_Landslide.setScaledContents(False)
        
        # --- FIXED LINE BELOW (Removed C++ syntax) ---
        self.Lable_Landslide.setAlignment(QtCore.Qt.AlignCenter)
        
        self.Lable_Landslide.setObjectName("Lable_Landslide")
        self.verticalLayout_4.addWidget(self.Lable_Landslide)
        self.GroupBox_File_Inputs = QtWidgets.QGroupBox(self.Widget_Inputs)
        self.GroupBox_File_Inputs.setStyleSheet("/* ======= File row: Browse button (left pill) ======= */\n"
"\n"
"\n"
"QPushButton {\n"
"    font:montserrat;\n"
"    border: 1px solid #3a3a3a;\n"
"    border-top-left-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background: #ffffff;\n"
"    color:black;\n"
"    padding: 6px 14px;\n"
"    font-weight: 10;\n"
"    font-size: 10px;\n"
"    min-height: 10;\n"
"    min-width: 55;\n"
"}\n"
"\n"
"/* ======= File row: Path field (right pill) ======= */\n"
"\n"
"QPlainTextEdit {\n"
"    border: 1px solid #3a3a3a;\n"
"    border-left: 0;                     /* fuse with the button */\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    background: #D5D5D5;\n"
"    padding: 0px 0px;\n"
"    min-height: 10;\n"
"    font-size: 10px;\n"
"    font-weight:10;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:hover { background: #f4f4f4; }\n"
"QPushButton:pressed { background: #eaeaea; }\n"
"QPushButton:disabled { color: #9b9b9b; background: #f6f6f6; }\n"
"\n"
"/* Optional: make text white in dark UIs */\n"
"QLabel { color: #black; }\n"
"QGroupBox { color: #202020; }\n"
"\n"
"")
        self.GroupBox_File_Inputs.setObjectName("GroupBox_File_Inputs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GroupBox_File_Inputs)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Label_Sentinel_2_Post_Event = QtWidgets.QLabel(self.GroupBox_File_Inputs)
        self.Label_Sentinel_2_Post_Event.setObjectName("Label_Sentinel_2_Post_Event")
        self.gridLayout_2.addWidget(self.Label_Sentinel_2_Post_Event, 3, 0, 1, 1)
        self.Widget_Sentinel_2_Post_Event = QtWidgets.QWidget(self.GroupBox_File_Inputs)
        self.Widget_Sentinel_2_Post_Event.setEnabled(True)
        self.Widget_Sentinel_2_Post_Event.setStyleSheet("")
        self.Widget_Sentinel_2_Post_Event.setObjectName("Widget_Sentinel_2_Post_Event")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Widget_Sentinel_2_Post_Event)
        self.horizontalLayout_9.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PushButton_Sentinel_2_Post_Event = QtWidgets.QPushButton(self.Widget_Sentinel_2_Post_Event)
        self.PushButton_Sentinel_2_Post_Event.setObjectName("PushButton_Sentinel_2_Post_Event")
        self.horizontalLayout_9.addWidget(self.PushButton_Sentinel_2_Post_Event)
        self.PTE_Sentinel_2_Post_Event = QtWidgets.QPlainTextEdit(self.Widget_Sentinel_2_Post_Event)
        self.PTE_Sentinel_2_Post_Event.setMaximumSize(QtCore.QSize(16777215, 25))
        self.PTE_Sentinel_2_Post_Event.setObjectName("PTE_Sentinel_2_Post_Event")
        self.horizontalLayout_9.addWidget(self.PTE_Sentinel_2_Post_Event)
        self.gridLayout_2.addWidget(self.Widget_Sentinel_2_Post_Event, 3, 1, 1, 1)
        self.Label_Sentinel_2_Pre_Event = QtWidgets.QLabel(self.GroupBox_File_Inputs)
        self.Label_Sentinel_2_Pre_Event.setObjectName("Label_Sentinel_2_Pre_Event")
        self.gridLayout_2.addWidget(self.Label_Sentinel_2_Pre_Event, 2, 0, 1, 1)
        self.Label_ROI = QtWidgets.QLabel(self.GroupBox_File_Inputs)
        self.Label_ROI.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Label_ROI.setObjectName("Label_ROI")
        self.gridLayout_2.addWidget(self.Label_ROI, 0, 0, 1, 1)
        self.Widget_ROI = QtWidgets.QWidget(self.GroupBox_File_Inputs)
        self.Widget_ROI.setStyleSheet("")
        self.Widget_ROI.setObjectName("Widget_ROI")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Widget_ROI)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PushButton_ROI = QtWidgets.QPushButton(self.Widget_ROI)
        self.PushButton_ROI.setObjectName("PushButton_ROI")
        self.horizontalLayout_4.addWidget(self.PushButton_ROI)
        self.PTE_ROI = QtWidgets.QPlainTextEdit(self.Widget_ROI)
        self.PTE_ROI.setMaximumSize(QtCore.QSize(16777215, 25))
        self.PTE_ROI.setPlainText("")
        self.PTE_ROI.setObjectName("PTE_ROI")
        self.horizontalLayout_4.addWidget(self.PTE_ROI)
        self.gridLayout_2.addWidget(self.Widget_ROI, 0, 1, 1, 1)
        self.Label_DEM = QtWidgets.QLabel(self.GroupBox_File_Inputs)
        self.Label_DEM.setObjectName("Label_DEM")
        self.gridLayout_2.addWidget(self.Label_DEM, 1, 0, 1, 1)
        self.Widget_DEM = QtWidgets.QWidget(self.GroupBox_File_Inputs)
        self.Widget_DEM.setStyleSheet("")
        self.Widget_DEM.setObjectName("Widget_DEM")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Widget_DEM)
        self.horizontalLayout_5.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PushButton_DEM = QtWidgets.QPushButton(self.Widget_DEM)
        self.PushButton_DEM.setObjectName("PushButton_DEM")
        self.horizontalLayout_5.addWidget(self.PushButton_DEM)
        self.PTE_DEM = QtWidgets.QPlainTextEdit(self.Widget_DEM)
        self.PTE_DEM.setMaximumSize(QtCore.QSize(16777215, 25))
        self.PTE_DEM.setObjectName("PTE_DEM")
        self.horizontalLayout_5.addWidget(self.PTE_DEM)
        self.gridLayout_2.addWidget(self.Widget_DEM, 1, 1, 1, 1)
        self.Widget_Sentinel_2_Pre_Event = QtWidgets.QWidget(self.GroupBox_File_Inputs)
        self.Widget_Sentinel_2_Pre_Event.setStyleSheet("")
        self.Widget_Sentinel_2_Pre_Event.setObjectName("Widget_Sentinel_2_Pre_Event")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Widget_Sentinel_2_Pre_Event)
        self.horizontalLayout_8.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PushButton_Sentinel_2_Pre_Event = QtWidgets.QPushButton(self.Widget_Sentinel_2_Pre_Event)
        self.PushButton_Sentinel_2_Pre_Event.setObjectName("PushButton_Sentinel_2_Pre_Event")
        self.horizontalLayout_8.addWidget(self.PushButton_Sentinel_2_Pre_Event)
        self.PTE_Sentinel_2_Pre_Event = QtWidgets.QPlainTextEdit(self.Widget_Sentinel_2_Pre_Event)
        self.PTE_Sentinel_2_Pre_Event.setMaximumSize(QtCore.QSize(16777215, 25))
        self.PTE_Sentinel_2_Pre_Event.setObjectName("PTE_Sentinel_2_Pre_Event")
        self.horizontalLayout_8.addWidget(self.PTE_Sentinel_2_Pre_Event)
        self.gridLayout_2.addWidget(self.Widget_Sentinel_2_Pre_Event, 2, 1, 1, 1)
        self.Widget_ROI.raise_()
        self.Label_ROI.raise_()
        self.Label_DEM.raise_()
        self.Widget_DEM.raise_()
        self.Label_Sentinel_2_Pre_Event.raise_()
        self.Widget_Sentinel_2_Pre_Event.raise_()
        self.Label_Sentinel_2_Post_Event.raise_()
        self.Widget_Sentinel_2_Post_Event.raise_()
        self.verticalLayout_4.addWidget(self.GroupBox_File_Inputs)
        self.GroupBox_Preview = QtWidgets.QGroupBox(self.Widget_Inputs)
        self.GroupBox_Preview.setObjectName("GroupBox_Preview")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.GroupBox_Preview)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.GroupBox_DEM_2 = QtWidgets.QGroupBox(self.GroupBox_Preview)
        self.GroupBox_DEM_2.setObjectName("GroupBox_DEM_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.GroupBox_DEM_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.GraphicsView_DEM_2 = QtWidgets.QGraphicsView(self.GroupBox_DEM_2)
        self.GraphicsView_DEM_2.setObjectName("GraphicsView_DEM_2")
        self.horizontalLayout_7.addWidget(self.GraphicsView_DEM_2)
        self.horizontalLayout_6.addWidget(self.GroupBox_DEM_2)
        self.GroupBox_ROI = QtWidgets.QGroupBox(self.GroupBox_Preview)
        self.GroupBox_ROI.setObjectName("GroupBox_ROI")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.GroupBox_ROI)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.GraphicsView_ROI = QtWidgets.QGraphicsView(self.GroupBox_ROI)
        self.GraphicsView_ROI.setObjectName("GraphicsView_ROI")
        self.horizontalLayout_10.addWidget(self.GraphicsView_ROI)
        self.horizontalLayout_6.addWidget(self.GroupBox_ROI)
        self.verticalLayout_4.addWidget(self.GroupBox_Preview)
        self.Widget_Footer_Buttons = QtWidgets.QWidget(self.Widget_Inputs)
        self.Widget_Footer_Buttons.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Widget_Footer_Buttons.setStyleSheet("QPushButton {\n"
"    font: montserrat;\n"
"    border: 1px solid #3a3a3a;\n"
"    border-top-left-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background: #ffffff;\n"
"    color:black;\n"
"    padding: 6px 14px;\n"
"    font-weight: 10;\n"
"    font-size: 10px;\n"
"    min-height: 10;\n"
"    min-width: 55;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover { background: #f4f4f4; }\n"
"QPushButton:pressed { background: #eaeaea; }\n"
"QPushButton:disabled { color: #9b9b9b; background: #f6f6f6; }")
        self.Widget_Footer_Buttons.setObjectName("Widget_Footer_Buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Widget_Footer_Buttons)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Button_Save = QtWidgets.QPushButton(self.Widget_Footer_Buttons)
        self.Button_Save.setObjectName("Button_Save")
        self.horizontalLayout_3.addWidget(self.Button_Save)
        self.Button_Detect = QtWidgets.QPushButton(self.Widget_Footer_Buttons)
        self.Button_Detect.setObjectName("Button_Detect")
        self.horizontalLayout_3.addWidget(self.Button_Detect)
        self.verticalLayout_4.addWidget(self.Widget_Footer_Buttons)
        self.verticalLayout_5.addWidget(self.Widget_Inputs)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.GridLayout_Inputs_Area.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.GridLayout_Inputs_Area)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GroupBox_Pre_Event.setTitle(_translate("MainWindow", "Pre - Event"))
        self.GroupBox_Post_Event.setTitle(_translate("MainWindow", "Post - Event"))
        self.GroupBox_NDVI.setTitle(_translate("MainWindow", "NDVI"))
        self.GroupBox_Result.setTitle(_translate("MainWindow", "Result"))
        self.Lable_Landslide.setText(_translate("MainWindow", "Landslide Detection"))
        self.GroupBox_File_Inputs.setTitle(_translate("MainWindow", "File Inputs"))
        self.Label_Sentinel_2_Post_Event.setText(_translate("MainWindow", "Post - Event:"))
        self.PushButton_Sentinel_2_Post_Event.setText(_translate("MainWindow", "Choose File"))
        self.Label_Sentinel_2_Pre_Event.setText(_translate("MainWindow", "Pre - Event:"))
        self.Label_ROI.setText(_translate("MainWindow", "ROI:"))
        self.PushButton_ROI.setText(_translate("MainWindow", "Choose File"))
        self.Label_DEM.setText(_translate("MainWindow", "DEM:"))
        self.PushButton_DEM.setText(_translate("MainWindow", "Choose File"))
        self.PushButton_Sentinel_2_Pre_Event.setText(_translate("MainWindow", "Choose File"))
        self.GroupBox_Preview.setTitle(_translate("MainWindow", "Preview"))
        self.GroupBox_DEM_2.setTitle(_translate("MainWindow", "DEM"))
        self.GroupBox_ROI.setTitle(_translate("MainWindow", "ROI"))
        self.Button_Save.setText(_translate("MainWindow", "SAVE"))
        self.Button_Detect.setText(_translate("MainWindow", "DETECT"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())